owner: oliverilp
repo: upptime

assignees:
  - oliverilp
sites:
#  - name: Nextcloud
#    url: https://cloud.oliverilp.ee/
  - name: Memos
    url: https://memos.oliverilp.ee/
  - name: Jellyfin
    url: https://crunchyroll.ee/

status-website:
  cname: status.oliverilp.ee
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "My Homelab Status"
  introMessage: "This is a uptime monitor and status page which uses real-time data powered entirely by GitHub. Response times vary based on GitHub Runner's proximity to my servers." 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
